In [1]:
#1)
import numpy as np
count = int(input())
array = np.arange(count)
#--------------------------
print("Массив до заданного значения",array)


 5


Массив до заданного значения [0 1 2 3 4]


In [2]:
#2)
#----- YOUR CODE HERE -----
import numpy as np
array_zero = np.array([0]*5)
array_one = np.array([1]*10)
#--------------------------
print("Массив из 0:\n",array_zero)
print("Массив из 1:\n",array_one)

# Альтернативно можно использовать np.zeros и np.ones

Массив из 0:
 [0 0 0 0 0]
Массив из 1:
 [1 1 1 1 1 1 1 1 1 1]


In [3]:
#3)
#----- YOUR CODE HERE -----
import numpy as np
count = int(input())
#--------------------------
print("2D массив где по диагонали присвоено значение Pi:\n",np.diag([np.pi]*count))

# Верно. Альтернатива: np.eye(count)*np.pi

In [6]:
#4)
#----- YOUR CODE HERE -----
import numpy as np
count = int(input())
matrix = np.full((count,count),False)
#--------------------------
print("2D массив ,заполненный значением FALSE:\n",matrix,"\nТип переменной:",)
type(matrix[0,0])

In [5]:
#5)
#----- YOUR CODE HERE -----
import numpy as np
array = np.arange(16)
new_array = np.copy(array)
for i in range(16):
    if(new_array[i] % 2 == 0):
        new_array[i] = 42
#--------------------------
# ИСХОДНЫЙ МАССИВ
print("Исходный массив:\n",array)
# НОВЫЙ МАССИВ
print("Новый массив:\n",new_array)

# Верно, но можно компактнее, например:
# arr = np.arange(16)
# arr[arr%2==0] = 42
# print(arr)

In [7]:
#6) 
#----- YOUR CODE HERE -----
import numpy as np
count_one = 0
index = 0
array_index=[]
array = np.random.randint(2 ,size=15)
#array = np.array([1]*15)
for i in range(15):
    if(array[i] == 1):
        count_one=count_one+1
        array_index.append(i)
#--------------------------
# ИСХОДНЫЙ МАССИВ
print("Исходный массив:\n",array)
# ИНДЕКСЫ
print("Индексы где находятся 1:\n",array_index)
# КОЛИЧЕСТВО
print("Количество 1:\n",count_one)

# Альтернатива:
# arr_index = np.nonzero(array)[0] ('[0]' для удобства, ибо nonzero возвращает кортеж)
# count_one = len(arr_index)

In [12]:
#7) 
#----- YOUR CODE HERE -----
import numpy as np
x3 = np.random.random((2,3, 4))
#--------------------------
print("Размерность: ",x3.ndim)
print("Количество элементов вдоль каждой размерности:",x3.shape)
print("Количество элементов в массиве:",x3.size)

In [8]:
#8)
#----- YOUR CODE HERE -----
import numpy as np
array = np.arange(9)
new_array = np.copy(array).reshape(3,3) 
#--------------------------
# ИСХОДНЫЙ МАССИВ
print("Исходный массив:\n",array)
# НОВЫЙ МАССИВ
print("Новый массив:\n",new_array)



In [9]:
#9)
#----- YOUR CODE HERE -----
import numpy as np
def func(array,row,col):
    if(row < np.size(array,0) or col<np.size(array,1)):
        row_sum = (array[row]).sum()
        col_sum = (array[0:(np.size(array, 0)),col]).sum()
        list = tuple([row_sum,col_sum])
        return list
    else:
        print("error")
array = np.random.randint(10, size=(4, 4))
print("Введите строку,чтобы её суммировать:")
row = int(input())
print(row)
print("Введите колонку,чтобы её суммировать:")
col = int(input())
print(col)
#--------------------------
print("2D массив:\n",array)
print(func(array,row,col))

# Чуть более аккуратная запись с индексами:
# row_sum = array[row, :].sum()
# col_sum = array[:, col].sum()

In [3]:
#10)
#----- YOUR CODE HERE -----
import numpy as np
def mat_mul(matrix1,matrix2):
    list = []
    if (np.size(matrix1, 1)==np.size(matrix2, 0)):
        for i in range(np.size(matrix1, 0)):
            for j in range(np.size(matrix2, 1)):
                list.append((matrix1[i]*matrix2[0:(np.size(array, 0)),j]).sum())
        list = (np.copy(list)).reshape((np.size(matrix1, 0)),(np.size(matrix2, 1)))
        return list
    else:
        print("inner dimensions does not match")

matrix1 = np.random.randint(10, size=(7, 4))
matrix2 = np.random.randint(10, size=(4, 7))
#--------------------------
print("A:\n",matrix1,"\n")
print("B:\n",matrix2,"\n")
print("Произведение матриц A*B:\n",mat_mul(matrix1,matrix2))

# В будущем если нужно будет перемножать матрицы, стоит обратить внимание
# на функции numpy.dot или numpy.matmul

A:
 [[6 4 1 6]
 [1 5 3 2]
 [1 3 3 2]
 [0 4 1 7]
 [6 1 8 4]
 [8 4 9 0]
 [7 6 9 5]] 

B:
 [[2 4 1 6 6 6 6]
 [7 5 7 3 3 7 9]
 [2 3 8 4 7 2 6]
 [5 9 1 1 9 8 1]] 

Произведение матриц A*B:
 [[ 72 101  48  58 109 114  84]
 [ 53  56  62  35  60  63  71]
 [ 39  46  48  29  54  49  53]
 [ 65  86  43  23  82  86  49]
 [ 55  89  81  75 131  91  97]
 [ 62  79 108  96 123  94 138]
 [ 99 130 126 101 168 142 155]]


In [16]:
#11)
#----- YOUR CODE HERE -----
import numpy as np
array = np.random.random(10)
max = array.max()
min = array.min()
mean = array.mean()
median = np.median(array)
#--------------------------
print(array)
print("Max value: %.3f\n\
Min value: %.3f\n\
Mean value: %.3f\n\
Median value: %.3f\n" % (max,min,mean,median))


In [9]:
#11)
#----- YOUR CODE HERE -----
import numpy as np
def comp_dist(array_one,array_two):
    result = np.sqrt(((array_one - array_two)**2).sum())
    return result
array_one = np.random.randint(10, size=(6))
array_two = np.random.randint(10, size=(6))
#--------------------------
print("Разность Евклидового расстояния между своей функцией и библиотечной:",np.linalg.norm(array_one-array_two) - comp_dist(array_one,array_two))
print("Евклидово расстояние:",comp_dist(array_one,array_two))